# Generated by Django 5.1.1 on 2024-10-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('data_created', models.DateField(auto_now_add=True)),
                ('deadline', models.DateField()),
                ('finished_data', models.DateField(null=True)),
            ],
        ),
    ]
